### ISSUE TITLE
Swift 3 support! 

### ISSUE THREAD

**Issue by mdabrarniyazi** [ayushn21/AvatarImageView#10]

**Comment by ayushn21** [comment]
Swift 3 is ready to go on a branch actually: https://github.com/ayushn21/AvatarImageView/tree/feature/swift-3

I haven't merged to master yet because CocoaPods didn't have Xcode 8 support until a couple of days ago. I'll try to merge it in asap. Until then please use the branch.

I'll leave this issue open until I've merged it into master.

**Comment by ayushn21** [comment]
Swift 3 is now merged to master and available through CocoaPods
